<?xml version="1.0" encoding="UTF-8" ?>
<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="1">
            <File firstVisibleLine="72" xOffset="0" scrollWidth="1664" startPos="1520" endPos="1476" selMode="0" offset="0" wrapCount="1" lang="HTML" encoding="-1" userReadOnly="no" filename="C:\xampp\htdocs\Website-PHP-Golden-Company\header.html" backupFilePath="" originalFileLastModifTimestamp="1408928281" originalFileLastModifTimestampHigh="30919142" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="-1571596717" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="50" xOffset="0" scrollWidth="5655" startPos="5847" endPos="5847" selMode="0" offset="0" wrapCount="1" lang="PHP" encoding="-1" userReadOnly="no" filename="C:\xampp\htdocs\Website-PHP-Golden-Company\index.php" backupFilePath="" originalFileLastModifTimestamp="2099455802" originalFileLastModifTimestampHigh="30919151" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="7471205" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="25" xOffset="0" scrollWidth="3185" startPos="588" endPos="49" selMode="0" offset="0" wrapCount="1" lang="PHP" encoding="-1" userReadOnly="no" filename="C:\xampp\htdocs\nsps\index.php" backupFilePath="" originalFileLastModifTimestamp="-1264325188" originalFileLastModifTimestampHigh="30917696" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="7471205" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1833" startPos="352" endPos="352" selMode="0" offset="0" wrapCount="1" lang="HTML" encoding="-1" userReadOnly="no" filename="C:\xampp\htdocs\Website-PHP-Golden-Company\footer.html" backupFilePath="" originalFileLastModifTimestamp="-686828383" originalFileLastModifTimestampHigh="30919143" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1" startPos="0" endPos="0" selMode="0" offset="0" wrapCount="1" lang="HTML" encoding="-1" userReadOnly="no" filename="C:\xampp\htdocs\Website-PHP-Golden-Company\history.html" backupFilePath="" originalFileLastModifTimestamp="1812720608" originalFileLastModifTimestampHigh="30918476" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="6619252" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1" startPos="0" endPos="0" selMode="0" offset="0" wrapCount="1" lang="PHP" encoding="-1" userReadOnly="no" filename="C:\xampp\htdocs\Website-PHP-Golden-Company\Menu do funcion&#x00E1;rio\checkFunc.php" backupFilePath="" originalFileLastModifTimestamp="-1803885741" originalFileLastModifTimestampHigh="30918476" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="-1571596717" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1" startPos="0" endPos="0" selMode="0" offset="0" wrapCount="1" lang="PHP" encoding="-1" userReadOnly="no" filename="C:\xampp\htdocs\Website-PHP-Golden-Company\Menu do funcion&#x00E1;rio\funcMenu.php" backupFilePath="" originalFileLastModifTimestamp="-2100198696" originalFileLastModifTimestampHigh="30918476" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1" startPos="0" endPos="0" selMode="0" offset="0" wrapCount="0" lang="PHP" encoding="-1" userReadOnly="no" filename="C:\xampp\htdocs\Website-PHP-Golden-Company\Menu do funcion&#x00E1;rio\newFunc.php" backupFilePath="" originalFileLastModifTimestamp="-1867804774" originalFileLastModifTimestampHigh="30918476" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="7602286" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1" startPos="0" endPos="0" selMode="0" offset="0" wrapCount="0" lang="PHP" encoding="-1" userReadOnly="no" filename="C:\xampp\htdocs\Website-PHP-Golden-Company\Menu do funcion&#x00E1;rio\userMsg.php" backupFilePath="" originalFileLastModifTimestamp="-1736605382" originalFileLastModifTimestampHigh="30918476" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="7602286" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1222" startPos="0" endPos="0" selMode="0" offset="0" wrapCount="1" lang="PHP" encoding="-1" userReadOnly="no" filename="C:\xampp\htdocs\nsps\header.php" backupFilePath="" originalFileLastModifTimestamp="-840625425" originalFileLastModifTimestampHigh="30915880" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>
